---
sudo: false
language: ruby
rvm:
  - 2.3.1
jdk:
  - openjdk7
before_install:
  - gem update --system
  - gem --version
install:
  - cd $TRAVIS_BUILD_DIR/src/logsearch-config
  - bin/install-dependencies
script:
  - bin/test default
notifications:
  email: false
